[project]
name = "cmeel-urdfdom"
version = "3.0.0"
description = "cmeel distribution for urdfdom, URDF parser"
readme = "urdfdom/README.md"
requires-python = ">= 3.8"
license = "BSD-3-Clause"

[project.urls]
homepage = "https://github.com/cmeel/cmeel-urdfdom"

[build-system]
requires = ["cmeel[build]", "cmeel-urdfdom-headers", "cmeel-tinyxml", "cmeel-console-bridge"]
build-backend = "cmeel.build"
source = "urdfdom"
configure_args = ["-DTIXML_USE_STL"]
